apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: deploy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller
      containers:
        - name: controller
          image: ghcr.io/ritz101411/deploy-controller
          ports:
            - containerPort: 3000
          env:
            - name: RUST_LOG
              value: "controller=info"